language: php 

compiler:
  - gcc
  - clang

os:
  - linux
#  - osx

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

notifications:
  email: 904208360@qq.com
   
env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

#Compile
before_script:
    - ./travis/compile.sh

script:
    - exit 0


